swagger design
SeferMirza/learn pull request #13
Opened 2022-04-18 10:43 UTC by SeferMirza

projenin kelimelerin çekileceği reponun api designı yapıldı

2022-04-18 11:02 UTC, cihandeniz requested changes
gorebildigim kadar review girdim

2022-04-18 11:02 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
> +          - cümle
bu feature onumuzde yok, design'i mevcut'a gore yapmis olalim, sal bunu

2022-04-18 11:02 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
> +      description: Kelimelerden bodydeki id'si eşleşen kelimeyi güncelle
body'den almaz id'yi, put/{id} seklinde bir istek olur, body'de yalnizca degerler olur, birmasa'daki swagger'a bak put ornegi icin, bir iki yerde vardi

2022-04-18 11:13 UTC, SeferMirza commented on docs/hangman-swagger-design.yaml
> +      description: Kelimelerden bodydeki id'si eşleşen kelimeyi güncelle
Açıklamayı program için yazmıştım. Program içerisinde verilmiş body içeriğini açıp query e veririz diye bu şekil yazmıştım

2022-04-18 11:23 UTC, SeferMirza commented on docs/hangman-swagger-design.yaml
> +      operationId: getWord
tam olarak bende bilmiyorum ama uniq olması gerekiyor. atılan isteği ayıt etmesini kolaylaştırmak için id veriyoruz diye düşündüm kullandım

2022-04-18 14:28 UTC, cihandeniz requested changes

2022-04-18 14:28 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
> +      operationId: getWord
tam ne oldugunu da ogrensen iyi olur, emin olalim

2022-04-18 14:28 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
>        operationId: putWord
burasi icin put/{id} demistim

sen input'lari output modellerden almissin
in-word-create ayri model olmali
digerleri out-word-s m l vs olmali

boylece word olustururken id almayabilirsin

2022-04-18 14:28 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
>        operationId: putWord
bi de turkce kalmis

2022-04-18 14:30 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
> +      description: Kelimelerden bodydeki id'si eşleşen kelimeyi güncelle
yok design karari bu, /put olmaz, hangi kayidi update edecegini url'den almali

2022-04-18 17:09 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
>    /words?level=1:
hata veriyor burasi

Semantic error at paths./words?level=1
Query strings in paths are not allowed.
[Jump to line 145]()

2022-04-19 10:42 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
> +      operationId: getWord
gonderdigin dokuman soyledigin seyi soylemiyor, request ile ilgili bir sey yazmiyor yani, operation'a bir sebepten id vererek baska yerlerde refer etmeni sagliyor diyor, niye link veriyoruz, link vermek ne demek onu da ayrica okumak lazim ama unique diye gorunce request olarak okumussun, konu request degil.

bence bunu buradan kaldir, bu olmak zorunda gibi gelmedi bana.

2022-04-19 11:55 UTC, cihandeniz reviewed
son bir review disinda her sey ok

2022-04-19 11:55 UTC, cihandeniz commented on docs/hangman-swagger-design.yaml
> +            type: integer
get words random donmemeli bence, normal siradan donmeli. ama random diye bir query parametre ekle bence, `random=true` denirse rastgele getirsin.

2022-04-19 14:03 UTC, merged